---
- hosts: slave
  become: true
  become_user: root
  tasks:
  - name: Install git & dependencies
    yum: name={{item}} state=present
    loop:
    - yum-utils
    - git
  - name: Install Docker
    yum: 
     name: docker
     state: present
  - name: start docker service
    service: 
     name: docker
     state: started 
     enabled: yes
